// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderApp.API.Infrastructure.Persistence;

#nullable disable

namespace OrderApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("OrderApp.API.Domain.Entities.Order", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("CustomerName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<DateTime>("OrderDate").IsRequired().HasColumnType("TEXT");
                b.Property<decimal>("TotalAmount").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("OrderDate");
                b.ToTable("Orders");
            });

            modelBuilder.Entity("OrderApp.API.Domain.Entities.OrderItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("OrderId").HasColumnType("INTEGER");
                b.Property<int>("ProductId").HasColumnType("INTEGER");
                b.Property<int>("Quantity").HasColumnType("INTEGER");
                b.Property<decimal>("UnitPrice").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.HasIndex("ProductId");
                b.ToTable("OrderItems", t =>
                {
                    t.HasCheckConstraint("CK_OrderItem_Quantity", "\"Quantity\" > 0");
                    t.HasCheckConstraint("CK_OrderItem_UnitPrice", "\"UnitPrice\" >= 0");
                });
            });

            modelBuilder.Entity("OrderApp.API.Domain.Entities.Product", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Sku").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<int>("StockQuantity").HasColumnType("INTEGER");
                b.Property<decimal>("UnitPrice").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("Sku").IsUnique();
                b.ToTable("Products", t =>
                {
                    t.HasCheckConstraint("CK_Product_StockQuantity", "\"StockQuantity\" >= 0");
                    t.HasCheckConstraint("CK_Product_UnitPrice", "\"UnitPrice\" >= 0");
                });
                b.HasData(
                    new { Id = 1, Name = "Mekanik Klavye",              Sku = "KB-001", StockQuantity = 50, UnitPrice = 1299.99m },
                    new { Id = 2, Name = "Kablosuz Mouse",              Sku = "MS-002", StockQuantity = 80, UnitPrice = 449.90m  },
                    new { Id = 3, Name = "27\" IPS Monitör",            Sku = "MN-003", StockQuantity = 20, UnitPrice = 5499.00m },
                    new { Id = 4, Name = "Kulaklık (Noise Cancelling)", Sku = "HP-004", StockQuantity = 35, UnitPrice = 2199.50m },
                    new { Id = 5, Name = "1080p Web Kamerası",          Sku = "WC-005", StockQuantity = 60, UnitPrice = 799.00m  }
                );
            });

            modelBuilder.Entity("OrderApp.API.Domain.Entities.OrderItem", b =>
            {
                b.HasOne("OrderApp.API.Domain.Entities.Order", "Order")
                    .WithMany("OrderItems").HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("OrderApp.API.Domain.Entities.Product", "Product")
                    .WithMany("OrderItems").HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Order");
                b.Navigation("Product");
            });

            modelBuilder.Entity("OrderApp.API.Domain.Entities.Order", b =>
                b.Navigation("OrderItems"));

            modelBuilder.Entity("OrderApp.API.Domain.Entities.Product", b =>
                b.Navigation("OrderItems"));
#pragma warning restore 612, 618
        }
    }
}
